from pathlib import Path


path = Path(
    "server/src/test/java/pl/grzegorz2047/standalonethewalls/server/identity/session/MinimalLobbyRuntimeTest.java"
)
content = path.read_text(encoding="utf-8")


def replace_once(old: str, new: str) -> None:
    global content
    count = content.count(old)
    if count != 1:
        raise RuntimeError(f"expected exactly one match, found {count}")
    content = content.replace(old, new, 1)


replace_once(
    "import pl.grzegorz2047.standalonethewalls.domain.lobby.LobbyConfiguration;\n"
    "import pl.grzegorz2047.standalonethewalls.identity.policy.HandleVerificationLevel;\n",
    "import pl.grzegorz2047.standalonethewalls.domain.lobby.LobbyConfiguration;\n"
    "import pl.grzegorz2047.standalonethewalls.domain.match.MatchConfiguration;\n"
    "import pl.grzegorz2047.standalonethewalls.identity.policy.HandleVerificationLevel;\n",
)
replace_once(
    "import pl.grzegorz2047.standalonethewalls.protocol.lobby.LobbyCommandResult;\n"
    "import pl.grzegorz2047.standalonethewalls.protocol.lobby.LobbyJoined;\n",
    "import pl.grzegorz2047.standalonethewalls.protocol.lobby.LobbyCommandResult;\n"
    "import pl.grzegorz2047.standalonethewalls.protocol.lobby.LobbyCountdownCancellationReason;\n"
    "import pl.grzegorz2047.standalonethewalls.protocol.lobby.LobbyJoined;\n"
    "import pl.grzegorz2047.standalonethewalls.protocol.lobby.LobbyMatchPhase;\n"
    "import pl.grzegorz2047.standalonethewalls.protocol.lobby.LobbyMatchPhaseSnapshot;\n"
    "import pl.grzegorz2047.standalonethewalls.protocol.lobby.LobbyMatchProtocolCodec;\n",
)
replace_once(
    "    @Test\n"
    "    void runtimeShutdownClosesOwnedSessionsAndReturnsEverySlot() throws InterruptedException {\n",
    "    @Test\n"
    "    void synchronizesCountdownCancellationRestartAndPreparationAcrossTwoSessions()\n"
    "            throws InterruptedException {\n"
    "        AuthorizedPlayerSessionQueue queue = queue(2);\n"
    "        TestSession alpha = new TestSession(1, playerId('a'), \"alpha\");\n"
    "        TestSession bravo = new TestSession(2, playerId('b'), \"bravo\");\n"
    "        enqueue(queue, alpha);\n"
    "        enqueue(queue, bravo);\n"
    "        MinimalLobbyRuntime lobby = countdownLobby(queue);\n"
    "\n"
    "        try {\n"
    "            lobby.start();\n"
    "            waitUntil(() -> lobby.memberCount() == 2);\n"
    "            readyTwoPlayers(alpha, bravo);\n"
    "            waitUntil(\n"
    "                    () ->\n"
    "                            latestMatchSnapshotUnchecked(alpha).phase()\n"
    "                                            == LobbyMatchPhase.START_COUNTDOWN\n"
    "                                    && latestMatchSnapshotUnchecked(alpha).ticksRemaining() == 3L\n"
    "                                    && latestMatchSnapshotUnchecked(alpha)\n"
    "                                            .equals(latestMatchSnapshotUnchecked(bravo)));\n"
    "\n"
    "            LobbyMatchPhaseSnapshot started = latestMatchSnapshotUnchecked(alpha);\n"
    "            assertThat(started.rosterRevision()).isEqualTo(6L);\n"
    "            assertThat(started.connectedPlayers()).isEqualTo(2);\n"
    "            assertThat(started.cancellationReason())\n"
    "                    .isEqualTo(LobbyCountdownCancellationReason.NONE);\n"
    "\n"
    "            assertThat(lobby.offerSimulationTick(0L)).isTrue();\n"
    "            waitUntil(() -> latestMatchSnapshotUnchecked(alpha).ticksRemaining() == 2L);\n"
    "            assertThat(latestMatchSnapshotUnchecked(alpha))\n"
    "                    .isEqualTo(latestMatchSnapshotUnchecked(bravo));\n"
    "\n"
    "            assertThat(lobby.offerSimulationTick(1L)).isTrue();\n"
    "            waitUntil(() -> latestMatchSnapshotUnchecked(alpha).ticksRemaining() == 1L);\n"
    "\n"
    "            sendReady(bravo, 3L, false);\n"
    "            waitForResult(bravo, 3L);\n"
    "            assertResult(bravo, 3L, 7L, LobbyCommandOutcome.APPLIED);\n"
    "            waitUntil(\n"
    "                    () ->\n"
    "                            latestMatchSnapshotUnchecked(alpha).phase()\n"
    "                                            == LobbyMatchPhase.WAITING_FOR_PLAYERS\n"
    "                                    && latestMatchSnapshotUnchecked(alpha).cancellationReason()\n"
    "                                            == LobbyCountdownCancellationReason.LOBBY_NOT_READY);\n"
    "            LobbyMatchPhaseSnapshot cancelled = latestMatchSnapshotUnchecked(alpha);\n"
    "            assertThat(cancelled).isEqualTo(latestMatchSnapshotUnchecked(bravo));\n"
    "            assertThat(cancelled.rosterRevision()).isEqualTo(7L);\n"
    "\n"
    "            assertThat(lobby.offerSimulationTick(2L)).isTrue();\n"
    "            sendReady(bravo, 4L, true);\n"
    "            waitForResult(bravo, 4L);\n"
    "            assertResult(bravo, 4L, 8L, LobbyCommandOutcome.APPLIED);\n"
    "            waitUntil(\n"
    "                    () ->\n"
    "                            latestMatchSnapshotUnchecked(alpha).phase()\n"
    "                                            == LobbyMatchPhase.START_COUNTDOWN\n"
    "                                    && latestMatchSnapshotUnchecked(alpha).ticksRemaining() == 3L\n"
    "                                    && latestMatchSnapshotUnchecked(alpha).revision()\n"
    "                                            > cancelled.revision());\n"
    "            LobbyMatchPhaseSnapshot restarted = latestMatchSnapshotUnchecked(alpha);\n"
    "            assertThat(restarted.authoritativeTick()).isEqualTo(2L);\n"
    "            assertThat(restarted).isEqualTo(latestMatchSnapshotUnchecked(bravo));\n"
    "\n"
    "            assertThat(lobby.offerSimulationTick(3L)).isTrue();\n"
    "            assertThat(lobby.offerSimulationTick(4L)).isTrue();\n"
    "            assertThat(lobby.offerSimulationTick(5L)).isTrue();\n"
    "            waitUntil(\n"
    "                    () ->\n"
    "                            latestMatchSnapshotUnchecked(alpha).phase()\n"
    "                                    == LobbyMatchPhase.PREPARATION);\n"
    "            LobbyMatchPhaseSnapshot preparation = latestMatchSnapshotUnchecked(alpha);\n"
    "            assertThat(preparation).isEqualTo(latestMatchSnapshotUnchecked(bravo));\n"
    "            assertThat(preparation.authoritativeTick()).isEqualTo(5L);\n"
    "            assertThat(matchSnapshotCount(alpha, LobbyMatchPhase.PREPARATION)).isOne();\n"
    "            assertThat(matchSnapshotCount(bravo, LobbyMatchPhase.PREPARATION)).isOne();\n"
    "\n"
    "            int rosterSnapshotsBeforeLockedCommand = snapshotCount(alpha);\n"
    "            sendSelect(alpha, 3L, LobbyTeam.RED);\n"
    "            waitForResult(alpha, 3L);\n"
    "            assertResult(alpha, 3L, 8L, LobbyCommandOutcome.MATCH_ALREADY_STARTED);\n"
    "            assertThat(snapshotCount(alpha)).isEqualTo(rosterSnapshotsBeforeLockedCommand);\n"
    "            assertThat(latestSnapshotUnchecked(alpha).revision()).isEqualTo(8L);\n"
    "\n"
    "            assertThat(lobby.offerSimulationTick(6L)).isTrue();\n"
    "            waitUntil(() -> lobby.matchSnapshot().phase().name().equals(\"PREPARATION\"));\n"
    "            assertThat(latestMatchSnapshotUnchecked(alpha).revision())\n"
    "                    .isEqualTo(preparation.revision());\n"
    "        } finally {\n"
    "            lobby.close();\n"
    "            queue.close();\n"
    "        }\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void joinDuringCountdownReceivesTheFullAuthoritativeCancellationState()\n"
    "            throws InterruptedException {\n"
    "        AuthorizedPlayerSessionQueue queue = queue(3);\n"
    "        TestSession alpha = new TestSession(1, playerId('a'), \"alpha\");\n"
    "        TestSession bravo = new TestSession(2, playerId('b'), \"bravo\");\n"
    "        TestSession charlie = new TestSession(3, playerId('c'), \"charlie\");\n"
    "        enqueue(queue, alpha);\n"
    "        enqueue(queue, bravo);\n"
    "        MinimalLobbyRuntime lobby = countdownLobby(queue);\n"
    "\n"
    "        try {\n"
    "            lobby.start();\n"
    "            waitUntil(() -> lobby.memberCount() == 2);\n"
    "            readyTwoPlayers(alpha, bravo);\n"
    "            waitUntil(\n"
    "                    () ->\n"
    "                            latestMatchSnapshotUnchecked(alpha).phase()\n"
    "                                    == LobbyMatchPhase.START_COUNTDOWN);\n"
    "\n"
    "            enqueue(queue, charlie);\n"
    "            waitUntil(\n"
    "                    () ->\n"
    "                            lobby.memberCount() == 3\n"
    "                                    && latestMatchSnapshotMessage(charlie).isPresent());\n"
    "\n"
    "            LobbyMatchPhaseSnapshot alphaSnapshot = latestMatchSnapshotUnchecked(alpha);\n"
    "            LobbyMatchPhaseSnapshot bravoSnapshot = latestMatchSnapshotUnchecked(bravo);\n"
    "            LobbyMatchPhaseSnapshot charlieSnapshot = latestMatchSnapshotUnchecked(charlie);\n"
    "            assertThat(alphaSnapshot).isEqualTo(bravoSnapshot).isEqualTo(charlieSnapshot);\n"
    "            assertThat(charlieSnapshot.phase()).isEqualTo(LobbyMatchPhase.WAITING_FOR_PLAYERS);\n"
    "            assertThat(charlieSnapshot.cancellationReason())\n"
    "                    .isEqualTo(LobbyCountdownCancellationReason.LOBBY_NOT_READY);\n"
    "            assertThat(charlieSnapshot.rosterRevision()).isEqualTo(7L);\n"
    "            assertThat(charlieSnapshot.connectedPlayers()).isEqualTo(3);\n"
    "            assertThat(latestSnapshotUnchecked(charlie).members()).hasSize(3);\n"
    "        } finally {\n"
    "            lobby.close();\n"
    "            queue.close();\n"
    "        }\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void shutdownDuringCountdownClosesEverySessionAndRejectsLaterTicks()\n"
    "            throws InterruptedException {\n"
    "        AuthorizedPlayerSessionQueue queue = queue(2);\n"
    "        TestSession alpha = new TestSession(1, playerId('a'), \"alpha\");\n"
    "        TestSession bravo = new TestSession(2, playerId('b'), \"bravo\");\n"
    "        enqueue(queue, alpha);\n"
    "        enqueue(queue, bravo);\n"
    "        MinimalLobbyRuntime lobby = countdownLobby(queue);\n"
    "\n"
    "        try {\n"
    "            lobby.start();\n"
    "            waitUntil(() -> lobby.memberCount() == 2);\n"
    "            readyTwoPlayers(alpha, bravo);\n"
    "            waitUntil(\n"
    "                    () ->\n"
    "                            latestMatchSnapshotUnchecked(alpha).phase()\n"
    "                                    == LobbyMatchPhase.START_COUNTDOWN);\n"
    "            assertThat(lobby.offerSimulationTick(0L)).isTrue();\n"
    "            waitUntil(() -> latestMatchSnapshotUnchecked(alpha).ticksRemaining() == 2L);\n"
    "\n"
    "            lobby.close();\n"
    "            lobby.close();\n"
    "\n"
    "            assertThat(lobby.isRunning()).isFalse();\n"
    "            assertThat(lobby.offerSimulationTick(1L)).isFalse();\n"
    "            assertThat(lobby.failure()).isEmpty();\n"
    "            assertThat(alpha.closeCount()).isEqualTo(1);\n"
    "            assertThat(bravo.closeCount()).isEqualTo(1);\n"
    "            assertThat(queue.activeTransferCount()).isZero();\n"
    "        } finally {\n"
    "            lobby.close();\n"
    "            queue.close();\n"
    "        }\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void runtimeShutdownClosesOwnedSessionsAndReturnsEverySlot() throws InterruptedException {\n",
)
replace_once(
    "    private static MinimalLobbyRuntime lobby(\n"
    "            AuthorizedPlayerSessionQueue queue, LobbyConfiguration configuration) {\n"
    "        return new MinimalLobbyRuntime(\n"
    "                queue, configuration, Duration.ofSeconds(1), Duration.ofSeconds(2), ignored -> {});\n"
    "    }\n",
    "    private static MinimalLobbyRuntime lobby(\n"
    "            AuthorizedPlayerSessionQueue queue, LobbyConfiguration configuration) {\n"
    "        return new MinimalLobbyRuntime(\n"
    "                queue, configuration, Duration.ofSeconds(1), Duration.ofSeconds(2), ignored -> {});\n"
    "    }\n"
    "\n"
    "    private static MinimalLobbyRuntime countdownLobby(AuthorizedPlayerSessionQueue queue) {\n"
    "        MatchConfiguration matchConfiguration =\n"
    "                new MatchConfiguration(2, 3, 2, 1, 2, 1, 2, 1, 1);\n"
    "        return new MinimalLobbyRuntime(\n"
    "                queue,\n"
    "                LobbyConfiguration.standard(),\n"
    "                matchConfiguration,\n"
    "                Duration.ofSeconds(1),\n"
    "                Duration.ofSeconds(2),\n"
    "                ignored -> {});\n"
    "    }\n"
    "\n"
    "    private static void readyTwoPlayers(TestSession alpha, TestSession bravo)\n"
    "            throws InterruptedException {\n"
    "        sendSelect(alpha, 1L, LobbyTeam.GREEN);\n"
    "        waitForResult(alpha, 1L);\n"
    "        assertResult(alpha, 1L, 3L, LobbyCommandOutcome.APPLIED);\n"
    "\n"
    "        sendSelect(bravo, 1L, LobbyTeam.BLUE);\n"
    "        waitForResult(bravo, 1L);\n"
    "        assertResult(bravo, 1L, 4L, LobbyCommandOutcome.APPLIED);\n"
    "\n"
    "        sendReady(alpha, 2L, true);\n"
    "        waitForResult(alpha, 2L);\n"
    "        assertResult(alpha, 2L, 5L, LobbyCommandOutcome.APPLIED);\n"
    "\n"
    "        sendReady(bravo, 2L, true);\n"
    "        waitForResult(bravo, 2L);\n"
    "        assertResult(bravo, 2L, 6L, LobbyCommandOutcome.APPLIED);\n"
    "    }\n",
)
replace_once(
    "    private static Optional<SentMessage> latestSnapshotMessage(TestSession session) {\n",
    "    private static int matchSnapshotCount(TestSession session, LobbyMatchPhase phase) {\n"
    "        return Math.toIntExact(\n"
    "                session.channel.sent().stream()\n"
    "                        .filter(\n"
    "                                message ->\n"
    "                                        message.messageType()\n"
    "                                                == MessageType.LOBBY_MATCH_SNAPSHOT)\n"
    "                        .map(\n"
    "                                message -> {\n"
    "                                    try {\n"
    "                                        return LobbyMatchProtocolCodec.decodeSnapshot(\n"
    "                                                message.payload());\n"
    "                                    } catch (LobbyProtocolException exception) {\n"
    "                                        throw new AssertionError(exception);\n"
    "                                    }\n"
    "                                })\n"
    "                        .filter(snapshot -> snapshot.phase() == phase)\n"
    "                        .count());\n"
    "    }\n"
    "\n"
    "    private static Optional<SentMessage> latestMatchSnapshotMessage(TestSession session) {\n"
    "        List<SentMessage> snapshots =\n"
    "                session.channel.sent().stream()\n"
    "                        .filter(\n"
    "                                message ->\n"
    "                                        message.messageType()\n"
    "                                                == MessageType.LOBBY_MATCH_SNAPSHOT)\n"
    "                        .toList();\n"
    "        return snapshots.isEmpty()\n"
    "                ? Optional.empty()\n"
    "                : Optional.of(snapshots.get(snapshots.size() - 1));\n"
    "    }\n"
    "\n"
    "    private static LobbyMatchPhaseSnapshot latestMatchSnapshot(TestSession session)\n"
    "            throws LobbyProtocolException {\n"
    "        return LobbyMatchProtocolCodec.decodeSnapshot(\n"
    "                latestMatchSnapshotMessage(session).orElseThrow().payload());\n"
    "    }\n"
    "\n"
    "    private static LobbyMatchPhaseSnapshot latestMatchSnapshotUnchecked(\n"
    "            TestSession session) {\n"
    "        try {\n"
    "            return latestMatchSnapshot(session);\n"
    "        } catch (LobbyProtocolException exception) {\n"
    "            throw new AssertionError(exception);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    private static Optional<SentMessage> latestSnapshotMessage(TestSession session) {\n",
)

path.write_text(content, encoding="utf-8")
