package pl.grzegorz2047.standalonethewalls.client.network;

/** Bounded public failure catalog for Direct Connect UI and release diagnostics. */
public enum DirectConnectFailureCode {
    SERVICE_CLOSED,
    ALREADY_CONNECTING,
    ALREADY_CONNECTED,
    CANCELLED,
    CONFIRMATION_INVALID,
    CONFIRMATION_EXPIRED,
    IDENTITY_STORAGE_FAILED,
    TRUST_STORAGE_FAILED,
    DNS_OR_CONNECT_FAILED,
    TLS_HANDSHAKE_FAILED,
    INVALID_SERVER_CERTIFICATE,
    CHANGED_SERVER_IDENTITY,
    EXPECTED_SERVER_IDENTITY_MISMATCH,
    SESSION_BOOTSTRAP_FAILED,
    IDENTITY_EXCHANGE_FAILED,
    ADMISSION_TIMEOUT,
    ADMISSION_MALFORMED,
    ADMISSION_REJECTED,
    LOBBY_JOIN_TIMEOUT,
    LOBBY_JOIN_MALFORMED,
    LOBBY_IDENTITY_MISMATCH,
    LOBBY_SNAPSHOT_TIMEOUT,
    LOBBY_SNAPSHOT_MALFORMED,
    LOBBY_SNAPSHOT_STALE,
    UNEXPECTED_MESSAGE,
    CONNECTION_CLOSED,
    INTERNAL_FAILURE
}
